services:
 
  db:
    image: mysql:9.2
    container_name: db
    restart: unless-stopped
    ports:
      - 3309:3306
      - 33090:33060
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - d:\mysqldata9:/var/lib/mysql
